### ISSUE TITLE
dependency problems chromium vs chromium browser... 

### ISSUE THREAD

**Issue by Havivw** [nccgroup/scrying#27]
hi i install chromium browser but still get that error and the tool work:

Selecting previously unselected package scrying.
(Reading database ... 142236 files and directories currently installed.)
Preparing to unpack scrying_0.8.1_amd64.deb ...
Unpacking scrying (0.8.1) ...
dpkg: dependency problems prevent configuration of scrying:
 scrying depends on chromium; however:
  Package chromium is not installed.

dpkg: error processing package scrying (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 scrying

but get that error while try to install another package:
scrying : Depends: chromium but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

 after run apt fix need to run dpkg again..

**Comment by sciguy16** [comment]
Thanks for reporting this! I've updated the debian package so that it can use either `chromium` or `chromium-browser`, because different distributions use different names for the package. The fix is in 0.8.2, which should automatically build shortly :)

**Comment by Havivw** [comment]
thanks man!!! you are the king!
