### ISSUE TITLE
PKGBUILD Already in BlackArch Linux

### ISSUE THREAD

**Issue by sepehrdaddev** [nccgroup/scrying#29]
Hi Developers of scrying,

We have noticed that you have packaged this tool for Arch Linux using BlackArch Linux PKGBUILDs.
We have already added this tool to our repository and you can find it [here](https://github.com/BlackArch/blackarch/commit/42706aff3198015cc0ba0e09004564bac4ed77f2).

you can easily install this tool with the help of BlackArch Linux repository on Arch Linux system.

Please check out our version of PKGBUILD.

Thanks

**Comment by sciguy16** [comment]
Awesome, thanks for including it :)
