### ISSUE TITLE
Image size/dimensions

### ISSUE THREAD

**Issue by HAE** [nccgroup/scrying#36]
Is there an option to control the dimensions of the screenshot?
I checked the [--help] option and read the Repo and Issues here but there is no mention of it.

If we're checking a couple of thousand urls, we may not need the current default of fullsize screenshots.
Please let me know if there is an undocumented option and if not, would you consider it in future updates?

Thanks for a great tool.

**Comment by sciguy16** [comment]
Hi! There isn't an option for specifying the screenshot size at the moment, but I'm in the process of redoing some of the web screenshotting code, and will add this as an option.

**Comment by HAE** [comment]
Thank you, much appreciated.

**Comment by sciguy16** [comment]
Reopening to make sure it gets tracked properly - it'll land at different times on Windows, Mac and Linux now that their implementations are different:

- [ ] Linux web
- [ ] Windows web
- [ ] Mac web
- [ ] RDP
- [ ] VNC

**Comment by sciguy16** [comment]
I have implemented this now - for web & RDP you can specify the size you would like:
```
scrying -t http://example.com --size 800x600
```

It has no effect on VNC because the server specifies the screen dimensions.
