### ISSUE TITLE
Allow authentication for vnc

### ISSUE THREAD

**Issue by bytebang** [nccgroup/scrying#38]
If the vnc connection is password protected and you know the password, then it is not possible to fetch an image ... because there is simply no way how to enter passwords

![image](https://user-images.githubusercontent.com/11525414/117622785-50ce8800-b173-11eb-8a0d-9344d2d95a83.png)

**Comment by sciguy16** [comment]
Thanks for the feature request! I'll add that when I have some available time :)

**Comment by sciguy16** [comment]
I've implemented support for this - an optional password can now be supplied with the `vnc-auth` argument:
```
scrying -t vnc://[::1] --vnc-auth password
```
