### ISSUE TITLE
Problems run on Windows

### ISSUE THREAD

**Issue by r00tsecc** [nccgroup/scrying#44]
When I run scryping on widows, it doesn't work and show errors.
"""
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: webview2 error, HRESULT 0x80070002', src\main.rs:209:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
"""

**Comment by sciguy16** [comment]
This was because scrying tried to use Edge WebView2 to render web pages, but it's not installed by default. I've since switched web screenshotting back to headless chrome to keep the code simpler and remove the unusual dependency so this should be resolved.
